/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashRouteImport } from './routes/_auth/dash'
import { Route as AuthCapturesNewRouteImport } from './routes/_auth/captures/new'
import { Route as AuthCapturesIdRouteImport } from './routes/_auth/captures/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashRoute = AuthDashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCapturesNewRoute = AuthCapturesNewRouteImport.update({
  id: '/captures/new',
  path: '/captures/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCapturesIdRoute = AuthCapturesIdRouteImport.update({
  id: '/captures/$id',
  path: '/captures/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dash': typeof AuthDashRoute
  '/captures/$id': typeof AuthCapturesIdRoute
  '/captures/new': typeof AuthCapturesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dash': typeof AuthDashRoute
  '/captures/$id': typeof AuthCapturesIdRoute
  '/captures/new': typeof AuthCapturesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/dash': typeof AuthDashRoute
  '/_auth/captures/$id': typeof AuthCapturesIdRoute
  '/_auth/captures/new': typeof AuthCapturesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/register' | '/dash' | '/captures/$id' | '/captures/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/dash' | '/captures/$id' | '/captures/new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/dash'
    | '/_auth/captures/$id'
    | '/_auth/captures/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dash': {
      id: '/_auth/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof AuthDashRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/captures/new': {
      id: '/_auth/captures/new'
      path: '/captures/new'
      fullPath: '/captures/new'
      preLoaderRoute: typeof AuthCapturesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/captures/$id': {
      id: '/_auth/captures/$id'
      path: '/captures/$id'
      fullPath: '/captures/$id'
      preLoaderRoute: typeof AuthCapturesIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashRoute: typeof AuthDashRoute
  AuthCapturesIdRoute: typeof AuthCapturesIdRoute
  AuthCapturesNewRoute: typeof AuthCapturesNewRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashRoute: AuthDashRoute,
  AuthCapturesIdRoute: AuthCapturesIdRoute,
  AuthCapturesNewRoute: AuthCapturesNewRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
